"""new fields on species

Revision ID: 151dca54bb38
Revises: 74520b823115
Create Date: 2026-05-08 23:24:32.997617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151dca54bb38'
down_revision = '74520b823115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bem', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brazilian_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('brazilian_type_synonym', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dna', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_column('dna')
        batch_op.drop_column('brazilian_type_synonym')
        batch_op.drop_column('brazilian_type')
        batch_op.drop_column('bem')

    # ### end Alembic commands ###
