"""init

Revision ID: 724366db099e
Revises: 
Create Date: 2026-05-08 23:15:38.848702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724366db099e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decay_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('growth_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('habitats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('nutrition_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('apa', sa.Text(), nullable=True),
    sa.CheckConstraint('doi IS NOT NULL OR url IS NOT NULL OR apa IS NOT NULL', name='ck_references_at_least_one_identifier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('scientific_name', sa.Text(), nullable=True),
    sa.Column('common_name', sa.Text(), nullable=True),
    sa.Column('type_country', sa.Text(), nullable=True),
    sa.Column('mycobank_index_fungorum_id', sa.BigInteger(), nullable=True),
    sa.Column('inaturalist_taxon_id', sa.BigInteger(), nullable=True),
    sa.Column('ncbi_taxonomy_id', sa.BigInteger(), nullable=True),
    sa.Column('unite_taxon_id', sa.BigInteger(), nullable=True),
    sa.Column('iucn_redlist', sa.Text(), nullable=True),
    sa.Column('mushroom_observer_name_id', sa.BigInteger(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_outdated_mycobank', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_inaturalist_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inaturalist_taxon_id'),
    sa.UniqueConstraint('mushroom_observer_name_id'),
    sa.UniqueConstraint('ncbi_taxonomy_id'),
    sa.UniqueConstraint('scientific_name', name='uq_species_scientific_name'),
    sa.UniqueConstraint('unite_taxon_id')
    )
    op.create_table('substrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('label_pt', sa.Text(), nullable=False),
    sa.Column('label_en', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("((role = 'admin') = is_admin)", name='ck_users_role_is_admin_consistent'),
    sa.CheckConstraint("role IN ('researcher', 'curator', 'admin')", name='ck_users_role_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('location_obscured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('quality_grade', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_observation_source_external_id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('idx_observation_source', ['source'], unique=False)
        batch_op.create_index('idx_observation_species_id', ['species_id'], unique=False)

    op.create_table('species_change_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('requester_name', sa.String(length=120), nullable=True),
    sa.Column('requester_email', sa.String(length=150), nullable=True),
    sa.Column('requester_institution', sa.String(length=150), nullable=True),
    sa.Column('request_note', sa.Text(), nullable=True),
    sa.Column('proposed_data', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'partial_approved', 'rejected')", name='ck_species_change_requests_status_valid'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species_change_requests', schema=None) as batch_op:
        batch_op.create_index('idx_species_change_requests_species', ['species_id'], unique=False)
        batch_op.create_index('idx_species_change_requests_status', ['status'], unique=False)

    op.create_table('species_characteristics',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('cultivation_possible', sa.Boolean(), nullable=True),
    sa.Column('cultivation', sa.Text(), nullable=True),
    sa.Column('cultivation_pt', sa.Text(), nullable=True),
    sa.Column('finding_tips', sa.Text(), nullable=True),
    sa.Column('finding_tips_pt', sa.Text(), nullable=True),
    sa.Column('nearby_trees', sa.Text(), nullable=True),
    sa.Column('nearby_trees_pt', sa.Text(), nullable=True),
    sa.Column('curiosities', sa.Text(), nullable=True),
    sa.Column('curiosities_pt', sa.Text(), nullable=True),
    sa.Column('general_description', sa.Text(), nullable=True),
    sa.Column('general_description_pt', sa.Text(), nullable=True),
    sa.Column('conservation_status', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('colors_pt', sa.Text(), nullable=True),
    sa.Column('size_cm', sa.Float(), nullable=True),
    sa.Column('season_start_month', sa.SmallInteger(), nullable=True),
    sa.Column('season_end_month', sa.SmallInteger(), nullable=True),
    sa.Column('iucn_assessment_year', sa.Text(), nullable=True),
    sa.Column('iucn_assessment_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id')
    )
    op.create_table('species_distributions',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'distribution_id')
    )
    op.create_table('species_photos',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('medium_url', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=True),
    sa.Column('license_code', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('rights_holder', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('declaration_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), server_default='iNaturalist', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'photo_id', name='pk_species_photo')
    )
    with op.batch_alter_table('species_photos', schema=None) as batch_op:
        batch_op.create_index('idx_species_photos_species', ['species_id'], unique=False)

    op.create_table('species_references',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reference_id'], ['references.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'reference_id')
    )
    op.create_table('species_similarities',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('similar_species_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('species_id <> similar_species_id', name='ck_species_similarity_not_self'),
    sa.ForeignKeyConstraint(['similar_species_id'], ['species.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'similar_species_id')
    )
    with op.batch_alter_table('species_similarities', schema=None) as batch_op:
        batch_op.create_index('idx_species_similarities_similar_species', ['similar_species_id'], unique=False)

    op.create_table('taxonomies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('classification_raw', sa.Text(), nullable=True),
    sa.Column('kingdom', sa.Text(), nullable=True),
    sa.Column('phylum', sa.Text(), nullable=True),
    sa.Column('class_name', sa.Text(), nullable=True),
    sa.Column('order', sa.Text(), nullable=True),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('genus', sa.Text(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('specific_epithet', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('basionym', sa.Text(), nullable=True),
    sa.Column('name_type', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('years_of_effective_publication', sa.Text(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('species_id', name='uq_taxonomies_species_id')
    )
    op.create_table('species_characteristics_decay_types',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('decay_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decay_type_id'], ['decay_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species_characteristics.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'decay_type_id')
    )
    with op.batch_alter_table('species_characteristics_decay_types', schema=None) as batch_op:
        batch_op.create_index('idx_scdt_decay_type_id', ['decay_type_id'], unique=False)

    op.create_table('species_characteristics_growth_forms',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('growth_form_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['growth_form_id'], ['growth_forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species_characteristics.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'growth_form_id')
    )
    with op.batch_alter_table('species_characteristics_growth_forms', schema=None) as batch_op:
        batch_op.create_index('idx_scgf_growth_form_id', ['growth_form_id'], unique=False)

    op.create_table('species_characteristics_habitats',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('habitat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habitat_id'], ['habitats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species_characteristics.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'habitat_id')
    )
    with op.batch_alter_table('species_characteristics_habitats', schema=None) as batch_op:
        batch_op.create_index('idx_sch_habitat_id', ['habitat_id'], unique=False)

    op.create_table('species_characteristics_nutrition_modes',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('nutrition_mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nutrition_mode_id'], ['nutrition_modes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['species_characteristics.species_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'nutrition_mode_id')
    )
    with op.batch_alter_table('species_characteristics_nutrition_modes', schema=None) as batch_op:
        batch_op.create_index('idx_scnm_nutrition_mode_id', ['nutrition_mode_id'], unique=False)

    op.create_table('species_characteristics_substrates',
    sa.Column('species_id', sa.BigInteger(), nullable=False),
    sa.Column('substrate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species_characteristics.species_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substrate_id'], ['substrates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('species_id', 'substrate_id')
    )
    with op.batch_alter_table('species_characteristics_substrates', schema=None) as batch_op:
        batch_op.create_index('idx_scs_substrate_id', ['substrate_id'], unique=False)

    op.create_table('species_photo_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('license_code', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('rights_holder', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('declaration_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_species_photo_requests_status_valid'),
    sa.ForeignKeyConstraint(['request_id'], ['species_change_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('species_photo_requests', schema=None) as batch_op:
        batch_op.create_index('idx_species_photo_requests_request', ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species_photo_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_species_photo_requests_request')

    op.drop_table('species_photo_requests')
    with op.batch_alter_table('species_characteristics_substrates', schema=None) as batch_op:
        batch_op.drop_index('idx_scs_substrate_id')

    op.drop_table('species_characteristics_substrates')
    with op.batch_alter_table('species_characteristics_nutrition_modes', schema=None) as batch_op:
        batch_op.drop_index('idx_scnm_nutrition_mode_id')

    op.drop_table('species_characteristics_nutrition_modes')
    with op.batch_alter_table('species_characteristics_habitats', schema=None) as batch_op:
        batch_op.drop_index('idx_sch_habitat_id')

    op.drop_table('species_characteristics_habitats')
    with op.batch_alter_table('species_characteristics_growth_forms', schema=None) as batch_op:
        batch_op.drop_index('idx_scgf_growth_form_id')

    op.drop_table('species_characteristics_growth_forms')
    with op.batch_alter_table('species_characteristics_decay_types', schema=None) as batch_op:
        batch_op.drop_index('idx_scdt_decay_type_id')

    op.drop_table('species_characteristics_decay_types')
    op.drop_table('taxonomies')
    with op.batch_alter_table('species_similarities', schema=None) as batch_op:
        batch_op.drop_index('idx_species_similarities_similar_species')

    op.drop_table('species_similarities')
    op.drop_table('species_references')
    with op.batch_alter_table('species_photos', schema=None) as batch_op:
        batch_op.drop_index('idx_species_photos_species')

    op.drop_table('species_photos')
    op.drop_table('species_distributions')
    op.drop_table('species_characteristics')
    with op.batch_alter_table('species_change_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_species_change_requests_status')
        batch_op.drop_index('idx_species_change_requests_species')

    op.drop_table('species_change_requests')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index('idx_observation_species_id')
        batch_op.drop_index('idx_observation_source')

    op.drop_table('observations')
    op.drop_table('users')
    op.drop_table('substrates')
    op.drop_table('species')
    op.drop_table('references')
    op.drop_table('nutrition_modes')
    op.drop_table('habitats')
    op.drop_table('growth_forms')
    op.drop_table('distributions')
    op.drop_table('decay_types')
    # ### end Alembic commands ###
