"""index uid and common_name

Revision ID: 74520b823115
Revises: 724366db099e
Create Date: 2026-05-08 23:17:53.041461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74520b823115'
down_revision = '724366db099e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_species_common_name', ['common_name'])
        batch_op.create_unique_constraint('uq_species_uid', ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.drop_constraint('uq_species_uid', type_='unique')
        batch_op.drop_constraint('uq_species_common_name', type_='unique')

    # ### end Alembic commands ###
